<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain\UnitOfMeasure.fs" />
    <Compile Include="Domain\UnitConversion.fs" />
    <Compile Include="Domain\Plant.fs" />
    <Compile Include="Domain\StockingPoint.fs" />
    <Compile Include="Domain\Node.fs" />
    <Compile Include="Domain\Sku.fs" />
    <Compile Include="Domain\BillofMaterials.fs" />
    <Compile Include="Domain\Routing.fs" />
    <Compile Include="Domain\TransportLeg.fs" />
    <Compile Include="Domain\ResourceGroup.fs" />
    <Compile Include="Domain\StandardResource.fs" />
    <Compile Include="Domain\PhysicalResource.fs" />

    <Compile Include="Application\UnitOfMeasure.fs" />
    <Compile Include="Application\UoMConversion.fs" />
    <Compile Include="Application\Plant.fs" />
    <Compile Include="Application\StockingPoint.fs" />
    <Compile Include="Application\Node.fs" />
    <Compile Include="Application\Sku.fs" />
    <Compile Include="Application\BillOfMaterials.fs" />
    <Compile Include="Application\Routing.fs" />
    <Compile Include="Application\TransportLeg.fs" />
    <Compile Include="Application\ResourceGroup.fs" />
    <Compile Include="Application\StandardResource.fs" />
    <Compile Include="Application\PhysicalResource.fs" />
    <Compile Include="BoundedContext.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Medhavi.SharedKernel\Medhavi.SharedKernel.fsproj" />
    <ProjectReference Include="..\Medhavi.Infrastructure\Medhavi.Infrastructure.fsproj" />
    <ProjectReference Include="..\Medhavi.Common\Medhavi.Common.fsproj" />
    <ProjectReference Include="..\Medhavi.Contracts\Medhavi.Contracts.fsproj" />
  </ItemGroup>

</Project>
