<Project>
  <!-- Code Coverage Settings -->
  <PropertyGroup>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <CoverletOutput>$(MSBuildProjectDirectory)/coverage.cobertura.xml</CoverletOutput>
    <Exclude>[*.Tests]*</Exclude>
    <ExcludeByAttribute>Obsolete;GeneratedCodeAttribute;CompilerGeneratedAttribute</ExcludeByAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>

