<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain.fs" />
    <Compile Include="Projections.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Medhavi.Common\Medhavi.Common.fsproj" />
    <ProjectReference Include="..\Medhavi.Contracts\Medhavi.Contracts.fsproj" />
    <ProjectReference Include="..\Medhavi.SharedKernel\Medhavi.SharedKernel.fsproj" />
    <ProjectReference Include="..\Medhavi.Infrastructure\Medhavi.Infrastructure.fsproj" />
  </ItemGroup>

</Project>
