<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="RzControls.fs" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Bolero" />
    <PackageReference Include="Radzen.Blazor" />
    <PackageReference Include="Microsoft.AspNetCore.Components" />
  </ItemGroup>

</Project>
