module Medhavi.Demand.Tests.Integration.ExplanationScenarioTests

open System
open System.Threading.Tasks
open Expecto
open Medhavi.Demand.Tests.Builders.ForecastPub
open Medhavi.SharedKernel
open Medhavi.SharedKernel.Contracts.Aggregate
open Medhavi.Contracts
open Medhavi.Contracts.Demand.DemandObservation
open Medhavi.Contracts.Demand.PlanningScope
open Medhavi.Contracts.Demand.Edp
open Medhavi.Contracts.Demand.ForecastPublication
open Medhavi.Contracts.Demand.PlanningClassificationAssignment
open Medhavi.Contracts.Demand.DemandBehaviourAssignment
open Medhavi.Contracts.Demand.PlanningPriorityAssignment
open Medhavi.Demand
open Medhavi.Demand.ForecastPublication.Model
open Medhavi.Demand.DemandIntelligenceContext
open Medhavi.Demand.Tests.Builders
open Medhavi.Demand.Tests.Builders.TestContext

// ────────────────────────────────────────────────
// Fake generator – deterministic, fast
// ────────────────────────────────────────────────
let private fakeExplanationText = "Fake explanation generated by test generator."
let private fakeGenerator = DemandExplanation.NaturalLanguageGenerator.fakeGenerator fakeExplanationText

let defaultEstablish: EstablishObservationReq =
    { ObservationId = "OBS-TEST-001"
      SkuId = "SKU-001"
      StockingPointId = "SP-001"
      Quantity = 100m
      UnitOfMeasure = "EA"
      ObservationType = SalesOrder
      BusinessTime = DateTimeOffset.UtcNow.AddHours(-1.0)
      CustomerId = None
      PromotionRef = None
      CampaignRef = None
      ContractRef = None
      SourceSystem = "ERP"
      ExternalRef = "ORD-001"
      MessageId = Guid.NewGuid().ToString()
      Revision = 1 }

let createFreshContext getAssessments isHighPriority getScopeId compService templateVersionRef realGenerator =
    let ctx = createContext getAssessments isHighPriority getScopeId compService templateVersionRef realGenerator None
    ctx.DemandIntelligenceContext

// ────────────────────────────────────────────────
// Fake tests – run on every CI build
// ────────────────────────────────────────────────
[<Tests>]
let fakeTests =
    testList
        "LLMExplanation (Fake)"
        [

          testCaseTask "Scenario 1: Why did my demand picture change?"
          <| fun () ->
              task {

                  let getHistory _ _ = Task.FromResult []
                  let compService = ForecastPublication.ComputationService.create getHistory
                  let isHighPriority _ = Task.FromResult false
                  let getScopeId _ _ = Task.FromResult(Some "SKU-001-SP-001-ALL-W-2027-27")
                  let getAssessments _ = task { return [] }

                  let ctx = createFreshContext getAssessments isHighPriority getScopeId compService "llm" fakeGenerator

                  // Build EDP v1 and v2
                  let obsReq1 =
                      { defaultEstablish with
                          ObservationId = "OBS-001"
                          Quantity = 100m }

                  let! _ = ctx.ObservationContext.Commands.Receive obsReq1

                  let! _ =
                      ctx.ObservationContext.Commands.Evaluate
                          { ObservationId = "OBS-001"
                            SignalId = None
                            SignalSource = None
                            SourceReliability = None
                            SignalTimestamp = None
                            SignalValue = None
                            StatisticalBound = None
                            RecentBaseline = None }

                  let! _ =
                      ctx.Workflow.DetermineScopeAndAssign
                          { ObservationId = "OBS-001"
                            PlanningScopeId = "" }
                          { SkuId = "SKU-001"
                            StockingPointId = "SP-001"
                            BucketType = "Weekly"
                            CustomerId = None
                            PlanningPeriod = PlanningWeek(2027, 27) }

                  let! _ =
                      ctx.Workflow.BuildAndPublishEdp
                          { PlanningScopeId = "SKU-001-SP-001-ALL-W-2027-27"
                            Period = PlanningWeek(2027, 27)
                            Quantity = 100m
                            ObservationId = "OBS-001" }

                  let obsReq2 =
                      { obsReq1 with
                          ObservationId = "OBS-002"
                          Quantity = 50m }

                  let! _ = ctx.ObservationContext.Commands.Receive obsReq2

                  let! _ =
                      ctx.ObservationContext.Commands.Evaluate
                          { ObservationId = "OBS-002"
                            SignalId = None
                            SignalSource = None
                            SourceReliability = None
                            SignalTimestamp = None
                            SignalValue = None
                            StatisticalBound = None
                            RecentBaseline = None }

                  let! _ =
                      ctx.Workflow.DetermineScopeAndAssign
                          { ObservationId = "OBS-002"
                            PlanningScopeId = "" }
                          { SkuId = "SKU-001"
                            StockingPointId = "SP-001"
                            BucketType = "Weekly"
                            CustomerId = None
                            PlanningPeriod = PlanningWeek(2027, 27) }

                  let! _ =
                      ctx.Workflow.BuildAndPublishEdp
                          { PlanningScopeId = "SKU-001-SP-001-ALL-W-2027-27"
                            Period = PlanningWeek(2027, 27)
                            Quantity = 50m
                            ObservationId = "OBS-002" }

                  // Record explanation for EDP v2
                  let! res =
                      ctx.DemandExplanationContext.Commands.RecordExplanation
                          { ExplanationId = "EXP-S1-001"
                            ExplainedArtifactType = "EnterpriseDemandPicture"
                            ExplainedArtifactId = "SKU-001-SP-001-ALL-W-2027-27"
                            Question = "Why did the EnterpriseDemandPicture change?"
                            BusinessTime = DateTimeOffset.UtcNow }

                  Expect.isOk res "RecordExplanation should succeed"

                  let! explOpt = ctx.DemandExplanationContext.Queries.GetById "EXP-S1-001"
                  Expect.isSome explOpt "Explanation should exist"

                  Expect.stringContains
                      explOpt.Value.NaturalLanguageExplanation
                      fakeExplanationText
                      "Should contain fake explanation"
              }

          testCaseTask "Scenario 1b: Why did my demand picture change? (Template Path)"
          <| fun () ->
              task {
                  let getHistory _ _ = Task.FromResult []
                  let compService = ForecastPublication.ComputationService.create getHistory
                  let isHighPriority _ = Task.FromResult false
                  let getScopeId _ _ = Task.FromResult(Some "SKU-001-SP-001-ALL-W-2027-27")
                  let getAssessments _ = task { return [] }

                  let ctx = createFreshContext getAssessments isHighPriority getScopeId compService "v1" fakeGenerator

                  // Build EDP v1 and v2
                  let obsReq1 =
                      { defaultEstablish with
                          ObservationId = "OBS-001"
                          Quantity = 100m }

                  let! _ = ctx.ObservationContext.Commands.Receive obsReq1

                  let! _ =
                      ctx.ObservationContext.Commands.Evaluate
                          { ObservationId = "OBS-001"
                            SignalId = None
                            SignalSource = None
                            SourceReliability = None
                            SignalTimestamp = None
                            SignalValue = None
                            StatisticalBound = None
                            RecentBaseline = None }

                  let! _ =
                      ctx.Workflow.DetermineScopeAndAssign
                          { ObservationId = "OBS-001"
                            PlanningScopeId = "" }
                          { SkuId = "SKU-001"
                            StockingPointId = "SP-001"
                            BucketType = "Weekly"
                            CustomerId = None
                            PlanningPeriod = PlanningWeek(2027, 27) }

                  let! _ =
                      ctx.Workflow.BuildAndPublishEdp
                          { PlanningScopeId = "SKU-001-SP-001-ALL-W-2027-27"
                            Period = PlanningWeek(2027, 27)
                            Quantity = 100m
                            ObservationId = "OBS-001" }

                  let obsReq2 =
                      { obsReq1 with
                          ObservationId = "OBS-002"
                          Quantity = 50m }

                  let! _ = ctx.ObservationContext.Commands.Receive obsReq2

                  let! _ =
                      ctx.ObservationContext.Commands.Evaluate
                          { ObservationId = "OBS-002"
                            SignalId = None
                            SignalSource = None
                            SourceReliability = None
                            SignalTimestamp = None
                            SignalValue = None
                            StatisticalBound = None
                            RecentBaseline = None }

                  let! _ =
                      ctx.Workflow.DetermineScopeAndAssign
                          { ObservationId = "OBS-002"
                            PlanningScopeId = "" }
                          { SkuId = "SKU-001"
                            StockingPointId = "SP-001"
                            BucketType = "Weekly"
                            CustomerId = None
                            PlanningPeriod = PlanningWeek(2027, 27) }

                  let! _ =
                      ctx.Workflow.BuildAndPublishEdp
                          { PlanningScopeId = "SKU-001-SP-001-ALL-W-2027-27"
                            Period = PlanningWeek(2027, 27)
                            Quantity = 50m
                            ObservationId = "OBS-002" }

                  // Record explanation for EDP v2
                  let! res =
                      ctx.DemandExplanationContext.Commands.RecordExplanation
                          { ExplanationId = "EXP-S1-002"
                            ExplainedArtifactType = "EnterpriseDemandPicture"
                            ExplainedArtifactId = "SKU-001-SP-001-ALL-W-2027-27"
                            Question = "Explain"
                            BusinessTime = DateTimeOffset.UtcNow }

                  Expect.isOk res "RecordExplanation should succeed"

                  let! explOpt = ctx.DemandExplanationContext.Queries.GetById "EXP-S1-002"
                  Expect.isSome explOpt "Explanation should exist"

                  Expect.stringContains
                      explOpt.Value.NaturalLanguageExplanation
                      "resulting in a total quantity changed by 150 units driven by the incorporation of OBS-001"
                      "Should contain template explanation text"
              }

          testCaseTask "Scenario 2: Why was this observation rejected?"
          <| fun () ->
              task {

                  let compService = ForecastPublication.ComputationService.create(fun _ _ -> Task.FromResult [])
                  let isHighPriority _ = Task.FromResult false
                  let getScopeId _ _ = Task.FromResult None
                  let getAssessments _ = task { return [] }

                  let ctx = createFreshContext getAssessments isHighPriority getScopeId compService "llm" fakeGenerator

                  // Ingest an observation with a signal that will be rejected
                  let obsReq =
                      { defaultEstablish with
                          ObservationId = "OBS-REJ-001"
                          Quantity = 200m }

                  let! _ = ctx.ObservationContext.Commands.Receive obsReq

                  let evalReq =
                      { ObservationId = "OBS-REJ-001"
                        SignalId = Some "SIG-001"
                        SignalSource = Some "TEST"
                        SourceReliability = Some 90m
                        SignalTimestamp = Some DateTimeOffset.UtcNow
                        SignalValue = Some 500m
                        StatisticalBound = Some 10m
                        RecentBaseline = Some 100m }

                  let! _ = ctx.ObservationContext.Commands.Evaluate evalReq // should reject

                  // Record explanation for the rejected observation
                  let! res =
                      ctx.DemandExplanationContext.Commands.RecordExplanation
                          { ExplanationId = "EXP-S2-001"
                            ExplainedArtifactType = "DemandObservation"
                            ExplainedArtifactId = "OBS-REJ-001"
                            Question = "Why was this observation rejected?"
                            BusinessTime = DateTimeOffset.UtcNow }

                  Expect.isOk res "RecordExplanation should succeed"

                  let! explOpt = ctx.DemandExplanationContext.Queries.GetById "EXP-S2-001"
                  Expect.isSome explOpt "Explanation should exist"

                  Expect.stringContains
                      explOpt.Value.NaturalLanguageExplanation
                      fakeExplanationText
                      "Should contain fake explanation"
              }

          testCaseTask "Scenario 3: What caused the forecast to be revised downward?"
          <| fun () ->
              task {

                  let getHistory _ _ = Task.FromResult [ 120m; 115m; 110m ]
                  let compService = ForecastPublication.ComputationService.create getHistory
                  let isHighPriority _ = Task.FromResult false
                  let getScopeId _ _ = Task.FromResult(Some "SCOPE-001")
                  let getAssessments _ = task { return [] }

                  let ctx = createFreshContext getAssessments isHighPriority getScopeId compService "llm" fakeGenerator

                  // Publish forecast v1
                  let initReq =
                      { defaultInitiateReq with
                          PublicationId = "PUB-F1"
                          PlanningScopeIds = [ "SKU-001-SP-001-ALL-W-2027-27" ] }

                  let! _ = ctx.ForecastContext.Commands.InitiateCycle initReq

                  let! _ =
                      ctx.ForecastContext.Commands.PrepareContext
                          { PublicationId = "PUB-F1"
                            Assumptions = []
                            Coverage =
                              [ { SkuId = "SKU-001"
                                  StockingPointId = "SP-001" } ] }

                  let! _ =
                      ctx.ForecastContext.Commands.SelectChampion
                          { PublicationId = "PUB-F1"
                            CandidateModelId = "M1"
                            EvaluationWindowStart = DateTimeOffset.UtcNow.AddDays(-30.0)
                            EvaluationWindowEnd = DateTimeOffset.UtcNow }

                  let! _ =
                      ctx.ForecastContext.Commands.GenerateBaseline
                          { PublicationId = "PUB-F1"
                            Forecasts = None }

                  let! _ = ctx.ForecastContext.Commands.Publish { PublicationId = "PUB-F1" }

                  // Now a second cycle with lower history
                  let getHistory2 _ _ = Task.FromResult [ 80m; 75m; 70m ]
                  let compService2 = ForecastPublication.ComputationService.create getHistory2

                  let ctx2 =
                      createFreshContext getAssessments isHighPriority getScopeId compService2 "llm" fakeGenerator

                  let! _ =
                      ctx2.ForecastContext.Commands.InitiateCycle
                          { defaultInitiateReq with
                              PublicationId = "PUB-F2"
                              PlanningScopeIds = [ "SKU-001-SP-001-ALL-W-2027-27" ] }

                  let! _ =
                      ctx2.ForecastContext.Commands.PrepareContext
                          { PublicationId = "PUB-F2"
                            Assumptions = []
                            Coverage =
                              [ { SkuId = "SKU-001"
                                  StockingPointId = "SP-001" } ] }

                  let! _ =
                      ctx2.ForecastContext.Commands.SelectChampion
                          { PublicationId = "PUB-F2"
                            CandidateModelId = "M2"
                            EvaluationWindowStart = DateTimeOffset.UtcNow.AddDays(-30.0)
                            EvaluationWindowEnd = DateTimeOffset.UtcNow }

                  let! _ =
                      ctx2.ForecastContext.Commands.GenerateBaseline
                          { PublicationId = "PUB-F2"
                            Forecasts = None }

                  let! _ = ctx2.ForecastContext.Commands.Publish { PublicationId = "PUB-F2" }

                  // Record explanation for the second publication
                  let! res =
                      ctx2.DemandExplanationContext.Commands.RecordExplanation
                          { ExplanationId = "EXP-S3-001"
                            ExplainedArtifactType = "ForecastPublication"
                            ExplainedArtifactId = "PUB-F2"
                            Question = "What caused the forecast to be revised downward?"
                            BusinessTime = DateTimeOffset.UtcNow }

                  Expect.isOk res "RecordExplanation should succeed"
                  let! explOpt = ctx2.DemandExplanationContext.Queries.GetById "EXP-S3-001"
                  Expect.isSome explOpt "Explanation should exist"

                  Expect.stringContains
                      explOpt.Value.NaturalLanguageExplanation
                      fakeExplanationText
                      "Should contain fake explanation"
              }

          testCaseTask "Scenario 4: Critical demand behaviour and automatic refresh"
          <| fun () ->
              task {
                  let getHistory _ _ = Task.FromResult []
                  let compService = ForecastPublication.ComputationService.create getHistory
                  let isHighPriority _ = Task.FromResult false
                  let getScopeId _ _ = Task.FromResult(Some "scope-SKU-001-SP-001")
                  let getAssessments _ = task { return [] }

                  let testCtx =
                      createContext getAssessments isHighPriority getScopeId compService "llm" fakeGenerator None

                  let ctx = testCtx.DemandIntelligenceContext

                  // Create published forecast older than 24h (same as Scenario 3 in integration tests)
                  let oldPub =
                      { defaultPub with
                          Id = ForecastPublicationId "PUB-OLD"
                          PlanningScopeIds = [ PlanningScopeId.fromString "scope-SKU-001-SP-001" |> okOrFail ]
                          Status = Published
                          TransactionTime = Timestamp.now - TimeSpan.FromHours 48.0
                          PublicationTime = Some(Timestamp.now - TimeSpan.FromHours 48.0) }

                  let! saveRes = testCtx.ForecastPublicationRepo.Save("PUB-OLD", oldPub, [])
                  saveRes |> okOrFail
                  DomainEventBus.Publish(ForecastPublicationPublished(oldPub, None))

                  // Seed assessment with corroboration
                  for i, source in [ "POS"; "WEB" ] |> List.indexed do
                      let! _ =
                          ctx.BehaviourAssessmentContext.Commands.EvaluateSignal
                              { SkuId = "SKU-001"
                                StockingPointId = "SP-001"
                                SignalId = $"sig-{i}"
                                Source = source
                                SourceReliability = 90m
                                Timestamp = DateTimeOffset.UtcNow.AddMinutes(-float i)
                                Value = 130m
                                StatisticalBound = 10m
                                RecentBaseline = 100m }

                      ()
                  // Critical signal
                  let! _ =
                      ctx.BehaviourAssessmentContext.Commands.EvaluateSignal
                          { SkuId = "SKU-001"
                            StockingPointId = "SP-001"
                            SignalId = "sig-critical"
                            Source = "MOBILE"
                            SourceReliability = 90m
                            Timestamp = DateTimeOffset.UtcNow
                            Value = 150m
                            StatisticalBound = 10m
                            RecentBaseline = 100m }

                  // Record explanation for the condition that was detected
                  let! res =
                      ctx.DemandExplanationContext.Commands.RecordExplanation
                          { ExplanationId = "EXP-S4-001"
                            ExplainedArtifactType = "DemandBehaviourAssessment"
                            ExplainedArtifactId = "SKU-001-SP-001"
                            Question = "What critical demand behaviour was detected?"
                            BusinessTime = DateTimeOffset.UtcNow }

                  Expect.isOk res "RecordExplanation should succeed"
                  let! explOpt = ctx.DemandExplanationContext.Queries.GetById "EXP-S4-001"
                  Expect.isSome explOpt "Explanation should exist"

                  Expect.stringContains
                      explOpt.Value.NaturalLanguageExplanation
                      fakeExplanationText
                      "Should contain fake explanation"
              }

          testCaseTask "Scenario 5: How was my planning priority determined?"
          <| fun () ->
              task {

                  let compService = ForecastPublication.ComputationService.create(fun _ _ -> Task.FromResult [])
                  let isHighPriority _ = Task.FromResult false
                  let getScopeId _ _ = Task.FromResult None
                  let getAssessments _ = task { return [] }

                  let ctx = createFreshContext getAssessments isHighPriority getScopeId compService "llm" fakeGenerator

                  // Classify, assign behaviour, assign priority
                  let! _ =
                      ctx.ClassificationContext.Commands.UpdateClassification
                          { EntityType = "Product"
                            EntityId = "SKU-001"
                            ClassificationType = "ABC" }

                  let! _ =
                      ctx.BehaviourAssignmentContext.Commands.UpdateBehaviour
                          { EntityType = "Product"
                            EntityId = "SKU-001"
                            BehaviourDimension = "StatisticalPattern" }

                  let! _ =
                      ctx.PriorityContext.Commands.UpdatePriority
                          { EntityType = "Product"
                            EntityId = "SKU-001" }

                  // Record explanation for priority assignment
                  let! res =
                      ctx.DemandExplanationContext.Commands.RecordExplanation
                          { ExplanationId = "EXP-S5-001"
                            ExplainedArtifactType = "PlanningPriorityAssignment"
                            ExplainedArtifactId = "Product-SKU-001"
                            Question = "How was my planning priority determined?"
                            BusinessTime = DateTimeOffset.UtcNow }

                  Expect.isOk res "RecordExplanation should succeed"
                  let! explOpt = ctx.DemandExplanationContext.Queries.GetById "EXP-S5-001"
                  Expect.isSome explOpt "Explanation should exist"

                  Expect.stringContains
                      explOpt.Value.NaturalLanguageExplanation
                      fakeExplanationText
                      "Should contain fake explanation"
              }

          testCaseTask "Scenario 6: Why did the system override my manual forecast?"
          <| fun () ->
              task {

                  let getHistory _ _ = Task.FromResult [ 100m ]
                  let compService = ForecastPublication.ComputationService.create getHistory
                  let isHighPriority _ = Task.FromResult false
                  let getScopeId _ _ = Task.FromResult(Some "SCOPE-001")
                  let getAssessments _ = task { return [] }

                  let ctx = createFreshContext getAssessments isHighPriority getScopeId compService "llm" fakeGenerator

                  // Create a forecast publication with an override
                  let initReq =
                      { defaultInitiateReq with
                          PublicationId = "PUB-OV"
                          PlanningScopeIds = [ "SKU-001-SP-001-ALL-W-2027-27" ] }

                  let! _ = ctx.ForecastContext.Commands.InitiateCycle initReq

                  let! _ =
                      ctx.ForecastContext.Commands.PrepareContext
                          { PublicationId = "PUB-OV"
                            Assumptions = []
                            Coverage =
                              [ { SkuId = "SKU-001"
                                  StockingPointId = "SP-001" } ] }

                  let! _ =
                      ctx.ForecastContext.Commands.SelectChampion
                          { PublicationId = "PUB-OV"
                            CandidateModelId = "M1"
                            EvaluationWindowStart = DateTimeOffset.UtcNow.AddDays(-30.0)
                            EvaluationWindowEnd = DateTimeOffset.UtcNow }

                  let! _ =
                      ctx.ForecastContext.Commands.GenerateBaseline
                          { PublicationId = "PUB-OV"
                            Forecasts = None }
                  // Record an override
                  let! _ =
                      ctx.ForecastContext.Commands.RecordOverride
                          { PublicationId = "PUB-OV"
                            ForecastId = "FC-SKU-001-SP-001"
                            NewValue = 420m
                            Justification = "Promotion running"
                            PlannerIdentity = "planner1" }

                  // Record explanation for the override
                  let! res =
                      ctx.DemandExplanationContext.Commands.RecordExplanation
                          { ExplanationId = "EXP-S6-001"
                            ExplainedArtifactType = "ForecastOverride"
                            ExplainedArtifactId = "PUB-OV"
                            Question = "Why did the system override my manual forecast?"
                            BusinessTime = DateTimeOffset.UtcNow }

                  Expect.isOk res "RecordExplanation should succeed"
                  let! explOpt = ctx.DemandExplanationContext.Queries.GetById "EXP-S6-001"
                  Expect.isSome explOpt "Explanation should exist"

                  Expect.stringContains
                      explOpt.Value.NaturalLanguageExplanation
                      fakeExplanationText
                      "Should contain fake explanation"
              } ]

// ────────────────────────────────────────────────
// Real Ollama tests – gated behind environment variable
// ────────────────────────────────────────────────
[<Tests>]
let realOllamaTests =

    testList
        "OllamaExplanation"
        [ testCaseTask "Scenario 1: Why did my demand picture change?"
          <| fun () ->
              task {
                  // let ollamaRunning = Environment.GetEnvironmentVariable "OLLAMA_RUNNING"
                  // if ollamaRunning <> "true" then
                  //     failwith "Skipping real Ollama test: OLLAMA_RUNNING not set"

                  let compService = ForecastPublication.ComputationService.create(fun _ _ -> Task.FromResult [])
                  let isHighPriority _ = Task.FromResult false
                  let getScopeId _ _ = Task.FromResult(Some "SKU-001-SP-001-ALL-W-2027-27")
                  let getAssessments _ = task { return [] }

                  use httpClient = new System.Net.Http.HttpClient()

                  let llmGenerator =
                      DemandExplanation.NaturalLanguageGenerator.createOllamaGenerator
                          httpClient
                          "http://localhost:11434"
                          "Qwen2.5:3B"

                  let ctx = createFreshContext getAssessments isHighPriority getScopeId compService "llm" llmGenerator

                  // Build EDP v1 and v2 (same as fake)
                  let obsReq1 =
                      { defaultEstablish with
                          ObservationId = "OBS-001"
                          Quantity = 100m }

                  let! _ = ctx.ObservationContext.Commands.Receive obsReq1

                  let! _ =
                      ctx.ObservationContext.Commands.Evaluate
                          { ObservationId = "OBS-001"
                            SignalId = None
                            SignalSource = None
                            SourceReliability = None
                            SignalTimestamp = None
                            SignalValue = None
                            StatisticalBound = None
                            RecentBaseline = None }

                  let! _ =
                      ctx.Workflow.DetermineScopeAndAssign
                          { ObservationId = "OBS-001"
                            PlanningScopeId = "" }
                          { SkuId = "SKU-001"
                            StockingPointId = "SP-001"
                            BucketType = "Weekly"
                            CustomerId = None
                            PlanningPeriod = PlanningWeek(2027, 27) }

                  let! _ =
                      ctx.Workflow.BuildAndPublishEdp
                          { PlanningScopeId = "SKU-001-SP-001-ALL-W-2027-27"
                            Period = PlanningWeek(2027, 27)
                            Quantity = 100m
                            ObservationId = "OBS-001" }

                  let obsReq2 =
                      { obsReq1 with
                          ObservationId = "OBS-002"
                          Quantity = 50m }

                  let! _ = ctx.ObservationContext.Commands.Receive obsReq2

                  let! _ =
                      ctx.ObservationContext.Commands.Evaluate
                          { ObservationId = "OBS-002"
                            SignalId = None
                            SignalSource = None
                            SourceReliability = None
                            SignalTimestamp = None
                            SignalValue = None
                            StatisticalBound = None
                            RecentBaseline = None }

                  let! _ =
                      ctx.Workflow.DetermineScopeAndAssign
                          { ObservationId = "OBS-002"
                            PlanningScopeId = "" }
                          { SkuId = "SKU-001"
                            StockingPointId = "SP-001"
                            BucketType = "Weekly"
                            CustomerId = None
                            PlanningPeriod = PlanningWeek(2027, 27) }

                  let! _ =
                      ctx.Workflow.BuildAndPublishEdp
                          { PlanningScopeId = "SKU-001-SP-001-ALL-W-2027-27"
                            Period = PlanningWeek(2027, 27)
                            Quantity = 50m
                            ObservationId = "OBS-002" }

                  let! res =
                      ctx.DemandExplanationContext.Commands.RecordExplanation
                          { ExplanationId = "EXP-REAL-1-001"
                            ExplainedArtifactType = "EnterpriseDemandPicture"
                            ExplainedArtifactId = "SKU-001-SP-001-ALL-W-2027-27"
                            Question = "Why did the EnterpriseDemandPicture change?"
                            BusinessTime = DateTimeOffset.UtcNow }

                  Expect.isOk res "RecordExplanation should succeed"
                  let! explOpt = ctx.DemandExplanationContext.Queries.GetById "EXP-REAL-1-001"
                  Expect.isSome explOpt "Explanation should exist"
                  printfn $"[Real LLM Scenario 1] %s{explOpt.Value.NaturalLanguageExplanation}"

                  Expect.isTrue
                      (explOpt.Value.NaturalLanguageExplanation.Length > 0)
                      "Explanation text must not be empty"
              }

          testCaseTask "Scenario 2: Real Ollama LLM explanation query"
          <| fun () ->
              task {
                  let getScopeId _ _ = Task.FromResult(Some "SCOPE-REAL")
                  let compService = ForecastPublication.ComputationService.create(fun _ _ -> Task.FromResult [])
                  let isHighPriority _ = Task.FromResult false
                  let getAssessments _ = task { return [] }
                  use httpClient = new System.Net.Http.HttpClient()

                  let llmGenerator =
                      DemandExplanation.NaturalLanguageGenerator.createOllamaGenerator
                          httpClient
                          "http://localhost:11434"
                          "Qwen2.5:3B"

                  let ctx = createFreshContext getAssessments isHighPriority getScopeId compService "llm" llmGenerator
                  // Execute record explanation request
                  let recordReq: Medhavi.Contracts.Demand.DemandLearning.RecordDemandExplanationReq =
                      { ExplanationId = "EXP-REAL-001"
                        ExplainedArtifactType = "EnterpriseDemandPicture"
                        ExplainedArtifactId = "SCOPE-REAL"
                        Question = "Why did the EnterpriseDemandPicture change?"
                        BusinessTime = DateTimeOffset.UtcNow }

                  let! res = ctx.DemandExplanationContext.Commands.RecordExplanation recordReq
                  Expect.isOk res "RecordExplanation with real generator should succeed"

                  // Query explanation state
                  let! explanationOpt = ctx.DemandExplanationContext.Queries.GetById "EXP-REAL-001"
                  Expect.isSome explanationOpt "Explanation should exist in projection"

                  // Assert that it generated a non-empty natural language explanation
                  Expect.isTrue
                      (explanationOpt.Value.NaturalLanguageExplanation.Length > 0)
                      "Explanation text must not be empty"
              } ]
