<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="IntegrationContractsTests.fs" />
    <Compile Include="IngestionTests.fs" />
    <Compile Include="Tests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Medhavi.Infrastructure\Medhavi.Infrastructure.fsproj" />
    <ProjectReference Include="..\..\Medhavi.Integration\Medhavi.Integration.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expecto" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Unquote" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

</Project>
