namespace Medhavi.Supply

open System
open Medhavi.SharedKernel
open Medhavi.MasterData
open Medhavi.Demand
open Medhavi.Capacity

/// Inventory Position (on-hand, safety stock rules)
type InventoryPosition = {
    SkuId: SkuId
    NodeId: NodeId
    OnHandQty: Qty
    SafetyStockQty: Qty
}

/// Planned Order (generated by MRP)
type PlannedOrderType =
    | PurchaseOrder
    | WorkOrder
    | TransferOrder

type PlannedOrder = {
    PlannedOrderId: string
    SkuId: SkuId
    NodeId: NodeId
    SourceNodeId: NodeId option // For TransferOrders
    Quantity: Qty
    ReleaseDate: DateTimeOffset
    DueDate: DateTimeOffset
    OrderType: PlannedOrderType
    IsFirmed: bool
}
