<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="CrossDomainEvents.fs" />
    
    <Compile Include="Core\UnitOfMeasure.fs" />
    <Compile Include="Core\Item.fs" />
    <Compile Include="Core\Location.fs" />
    <Compile Include="Core\Customer.fs" />
    <Compile Include="Core\Supplier.fs" />
    <Compile Include="Core\PlanningScope.fs" />
    <Compile Include="Core\Calendar.fs" />
    <Compile Include="Core\PlanningPeriod.fs" />
    <Compile Include="Core\EnterprisePicture.fs" />
    <Compile Include="Core\Demand.fs" />
    <Compile Include="Core\Exception.fs" />

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.SystemTextJson" />
  </ItemGroup>
</Project>
